import { HttpClient} from '@angular/common/http';

import { Injectable } from '@angular/core';
import { pelicula } from '../models/interfaces';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor( private http : HttpClient) { }


  getMovies(){
    return this.http.get('https://api.themoviedb.org/3/discover/movie?primary_release_date.gte=2021-01-15&primary_release_date.lte=2021-07-22&api_key=8cc51acc98d88f55d5eed5fba2e1377c&language=es&include_image_language=es')
  }


//JSON optenido del api de https://www.themoviedb.org
  movies = [
    {
        "adult": false,
        "backdrop_path": "/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",
        "genre": "Accion" ,
        "id": 581726,
        "original_language": "en",
        "original_title": "Infinite",
        "overview": "Evan McCauley tiene habilidades que nunca aprendió y recuerdos de lugares que nunca ha visitado. Automedicado y al borde de un colapso mental, un grupo secreto que se hace llamar \"Infinitos\" acuden a su rescate, revelando que sus recuerdos son reales.",
        "popularity": 2995.333,
        "poster_path": "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
        "release_date": "2021-06-10",
        "title": "Infinito",
        "video": false,
        "vote_average": 7.3,
        "vote_count": 636,
        "trailer": "UKFjeglbNDg"
    },
    {
        "adult": false,
        "backdrop_path": "/dq18nCTTLpy9PmtzZI6Y2yAgdw5.jpg",
        "genre": "Accion" ,
        "id": 497698,
        "original_language": "en",
        "original_title": "Black Widow",
        "overview": "Natasha Romanoff, alias Viuda Negra, se enfrenta a las partes más oscuras de su historia cuando surge una peligrosa conspiración con vínculos con su pasado. Perseguida por una fuerza que no se detendrá ante nada para acabar con ella, Natasha debe enfrentarse a su historia como espía y a las relaciones rotas que dejó a su paso mucho antes de convertirse en una Vengadora.",
        "popularity": 2981.934,
        "poster_path": "/qjAsDcMlHXxJSfNDQGK9hs13US0.jpg",
        "release_date": "2021-07-07",
        "title": "Viuda negra",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 4101,
        "trailer": "HlB_8y3cmUg"
    },
 
    {
        "adult": false,
        "backdrop_path": "/8s4h9friP6Ci3adRGahHARVd76E.jpg",
        "genre": "Animado" ,
        "id": 379686,
        "original_language": "en",
        "original_title": "Space Jam: A New Legacy",
        "overview": "Secuela de la cinta original de 1996, Space Jam, protagonizada por Michael Jordan. En esta segunda parte, la super estrella de la NBA es LeBron James, quien queda atrapado junto a su hijo Dom en un extraño lugar, un espacio digital de una fuerza todopoderosa y malvada conocida como A.I. Para volver a casa y poner a salvo a su hijo, el jugador de baloncesto deberá unir fuerzas con Bugs Bunny, Lola Bunny y el resto de personajes de los Looney Tunes para enfrentarse en un partido de baloncesto a los campeones digitalizados por A.I.",
        "popularity": 2426.189,
        "poster_path": "/uHDF2320SbWDTP1FMZ8LgEIHew2.jpg",
        "release_date": "2021-07-08",
        "title": "Space Jam: Nuevas leyendas",
        "video": false,
        "vote_average": 7.6,
        "vote_count": 1668,
        "trailer":"z7PSyWuArVQ"
    },
    {
        "adult": false,
        "backdrop_path": "/gX5UrH1TLVVBwI7WxplW43BD6Z1.jpg",
        "genre": "Animado" ,
        "id": 459151,
        "original_language": "en",
        "original_title": "The Boss Baby: Family Business",
        "overview": "Los hermanos Templeton se han convertido en adultos y se han alejado el uno del otro, pero un nuevo jefe bebé con un enfoque de vanguardia está a punto de unirlos nuevamente e inspirar un nuevo negocio familiar.",
        "popularity": 1903.643,
        "poster_path": "/3XYeAnIdjTiHZehtKcNzsyBwtcz.jpg",
        "release_date": "2021-07-01",
        "title": "El Bebé Jefazo 2: Negocios de familia",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 1135,
        "trailer":"-wzK-lLFrZI"
    },
    {
        "adult": false,
        "backdrop_path": "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
        "genre": "Animado" ,
        "id": 508943,
        "original_language": "en",
        "original_title": "Luca",
        "overview": "Ambientada en un precioso pueblo costero de la Riviera italiana, narra la historia sobre el paso a la edad adulta de un chico que vive un verano inolvidable lleno de helados, pasta e infinitos paseos en scooter. Luca comparte estas aventuras con su nuevo mejor amigo, pero toda la diversión se ve amenazada por un secreto muy profundo: él es un monstruo marino de un mundo que yace bajo la superficie del agua.",
        "popularity": 1856.216,
        "poster_path": "/j93NHWoTjdsL4sdz058M3AvKrMy.jpg",
        "release_date": "2021-06-17",
        "title": "Luca",
        "video": false,
        "vote_average": 8.1,
        "vote_count": 3790,
        "trailer":"3zush7bttCI"
    },
    {
        "adult": false,
        "backdrop_path": "/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg",
        "genre": "Accion" ,
        "id": 588228,
        "original_language": "en",
        "original_title": "The Tomorrow War",
        "overview": "Un día el mundo se paraliza cuando un grupo de viajeros en el tiempo se transporta desde el año 2051 para entregar un mensaje urgente: La humanidad está perdiendo la guerra mundial contra una especie alienígena letal. La única esperanza de supervivencia es que los soldados y los ciudadanos del presente sean transportados al futuro y se unan a la lucha. Entre los reclutados está el profesor de instituto y padre de familia Dan Forester (Chris Pratt) quien, decidido a salvar el mundo por su hija, se une a una brillante científica (Yvonne Strahovski) y a su padre (J.K. Simmons) en una búsqueda desesperada por reescribir el destino del planeta.",
        "popularity": 1842.832,
        "poster_path": "/tzp6VzED2TBc02bkYoYnQa6r2OK.jpg",
        "release_date": "2021-06-30",
        "title": "La guerra del mañana",
        "video": false,
        "vote_average": 8.2,
        "vote_count": 3360,
        "trailer":"3_lWvRyXOsY"
    },
    {
        "adult": false,
        "backdrop_path": "/wPjtacig0kIkVcTQmXoNt6jbMwo.jpg",
        "genre": "Accion" ,
        "id": 617502,
        "original_language": "en",
        "original_title": "Jolt",
        "overview": "Lindy es una mujer con un doloroso secreto: debido a un raro trastorno neurológico crónico, experimenta esporádicos impulsos de ira extremadamente violentos que solo pueden detenerse cuando se aplica una descarga a sí misma con un dispositivo especial de electrodos. Aunque es incapaz de encontrar el amor y de encajar en un mundo que teme su extraña condición, por fin logra confiar lo suficiente en un hombre como para enamorarse, solo para encontrarlo muerto al día siguiente. Desconsolada y enfurecida, se embarca en una misión de venganza para encontrar a su asesino, mientras es perseguida por la policía como principal sospechosa del crimen.",
        "popularity": 1648.405,
        "poster_path": "/gYZAHan5CHPFXORpQMvOjCTug4E.jpg",
        "release_date": "2021-07-15",
        "title": "Jolt",
        "video": false,
        "vote_average": 6.8,
        "vote_count": 462,
        "trailer":"jVWHqqd39cM"

    },
    {
        "adult": false,
        "backdrop_path": "/tehpKMsls621GT9WUQie2Ft6LmP.jpg",
        "genre": "Suspenso" ,
        "id": 602223,
        "original_language": "en",
        "original_title": "The Forever Purge",
        "overview": "Para los miembros de un movimiento clandestino, ya no es suficiente una noche anual de anarquía y asesinatos, así que deciden devolver a Estados Unidos el caos y las masacres sin fin, donde nadie volverá a estar a salvo... jamás. Adela y su esposo Juan viven en Texas, donde él trabaja como peón en un rancho para la adinerada familia Tucker. En la mañana después de la tradicional purga, una banda de asesinos enmascarados ataca violenta e ilegalmente a la familia Tucker. Tras este hecho, la familia texana se ve obligada a unirse con Juan y su esposa para enfrentar un país entero a punto de colapsar, que se hunde en un mar de caos y de sangre. Quinta y última entrega de la saga 'The Purge'.",
        "popularity": 1461.295,
        "poster_path": "/5yvawJviOjb2nUFvHGXcCpGVTqy.jpg",
        "release_date": "2021-06-30",
        "title": "La Purga: Infinita",
        "video": false,
        "vote_average": 7.6,
        "vote_count": 915,
        "trailer":"SfGk9cuvgx8"
    },
    {
        "adult": false,
        "backdrop_path": "/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg",
        "genre": "Accion" ,
        "id": 337404,
        "original_language": "en",
        "original_title": "Cruella",
        "overview": "Ambientada en el Londres de los años 70, en plena revolución del punk rock, muestra a una joven estafadora llamada Estella, una chica inteligente y creativa, decidida a convertirse en una exitosa diseñadora de moda, que se asocia con un par de ladrones para sobrevivir en las calles de la capital británica. Pero cuando su talento para la moda llama la atención de la legendaria diseñadora, la Baronesa von Hellman, Estella cambia el rumbo de su vida hasta que una serie de acontecimientos y revelaciones que harán que Estella asuma su lado malvado y se convierta en la estridente, moderna y vengativa Cruella de Vil.",
        "popularity": 1188.451,
        "poster_path": "/23F18NlCcYdX2kpHE2KZuWye7Lk.jpg",
        "release_date": "2021-05-26",
        "title": "Cruella",
        "video": false,
        "vote_average": 8.4,
        "vote_count": 4675,
        "trailer":"oK13SZYZqmA"
    },
    {
        "adult": false,
        "backdrop_path": "/heMC3jAjQPNSlr1n9mZKUQ58EOE.jpg",
        "genre": "Accion" ,
        "id": 672322,
        "original_language": "ja",
        "original_title": "るろうに剣心 最終章 The Beginning",
        "overview": "Kenshin Himura inicia la búsqueda de un misterioso traficante de armas llamado Enishi Yukishiro que controla el bajo mundo de China. Durante su misión se desvelará también el secreto de \"Jujishou\", un elemento íntimamente ligado al propio Himura.",
        "popularity": 1103.697,
        "poster_path": "/a7cWay8MBxGbgvFI8HN5FhJsPAX.jpg",
        "release_date": "2021-06-04",
        "title": "Kenshin, el guerrero samurái: El principio",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 80,
        "trailer":"8WO9pJfDFnk"
    },
    {
        "adult": false,
        "backdrop_path": "/77tui163estZrQ78NBggqDB4n2C.jpg",
        "genre": "Accion" ,
        "id": 637649,
        "original_language": "en",
        "original_title": "Wrath of Man",
        "overview": "H (Jason Statham) es el misterioso tipo que acaba de incorporarse como guardia de seguridad en una compañía de blindados. Durante un intento de atraco a su camión, sorprende a sus compañeros mostrando habilidades de un soldado profesional, dejando al resto del equipo preguntándose quién es realmente y de dónde viene. Pronto se hará claro el verdadero motivo por el cual H está buscando un ajuste de cuentas.",
        "popularity": 991.204,
        "poster_path": "/fvqIv59EgwY7lJ5QfqSWpCxOFxK.jpg",
        "release_date": "2021-04-22",
        "title": "Despierta la furia",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 1839,
        "trailer":"CQgBahCGHUk"
    },
    {
        "adult": false,
        "backdrop_path": "/iJ2HVOZT9Kjayrhy21pbGIJs9ey.jpg",
        "genre": "Accion" ,
        "id": 525660,
        "original_language": "cn",
        "original_title": "真·三国无双",
        "overview": "Dynasty Warriors es una próxima película de acción y fantasía de Hong Kong basada en la franquicia japonesa de videojuegos del mismo título.",
        "popularity": 980.425,
        "poster_path": "/1w0AkplNn51VZZ9ehA9I0hqJzLs.jpg",
        "release_date": "2021-04-29",
        "title": "Dynasty Warriors",
        "video": false,
        "vote_average": 6.3,
        "vote_count": 51,
        "trailer":"K8pyNXNtZBM"
    },
 
    {
        "adult": false,
        "backdrop_path": "/c0izdYdnTe4uMRifHgvTA85wPz0.jpg",
        "genre": "Accion" ,
        "id": 503736,
        "original_language": "en",
        "original_title": "Army of the Dead",
        "overview": "Un grupo de mercenarios decide llevar a cabo el mayor atraco que jamás se haya realizado en la ciudad de Las Vegas, Nevada justo después de que se produzca una epidemia de muertos vivientes. Para ello tendrán que adentrarse en una zona de cuarentena, con los riesgos que ello conlleva.",
        "popularity": 886.328,
        "poster_path": "/4h1Uc13QPjHTTUX0bikICWUxTSV.jpg",
        "release_date": "2021-05-14",
        "title": "Ejército de los muertos",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 2137,
        "trailer":"Li7AzMfuCkA"
    },
    {
        "adult": false,
        "backdrop_path": "/3OwaKVZf3A2NdnarqKbwzFEhKir.jpg",
        "genre": "Animado" ,
        "id": 730840,
        "original_language": "en",
        "original_title": "Trollhunters: Rise of the Titans",
        "overview": "Los héroes de la serie Trollhunters se unen en una épica aventura para luchar contra la Orden de los Arcanos para determinar quién controla el poder de la magia que los une a todos.",
        "popularity": 864.391,
        "poster_path": "/zvUNFeTz0Sssb210wSiIiHRjA4W.jpg",
        "release_date": "2021-07-21",
        "title": "Trollhunters: El despertar de los titanes",
        "video": false,
        "vote_average": 7.9,
        "vote_count": 140,
        "trailer":"Qi2_6-VzYcw"
    },
    {
        "adult": false,
        "backdrop_path": "/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
        "genre": "Accion" ,
        "id": 460465,
        "original_language": "en",
        "original_title": "Mortal Kombat",
        "overview": "Un boxeador fracasado descubre un secreto familiar que lo lleva a un torneo místico llamado Mortal Kombat donde se encuentra con un grupo de guerreros que luchan hasta la muerte para salvar los reinos del malvado hechicero Shang Tsung.",
        "popularity": 847.35,
        "poster_path": "/t2GbiMJfO8txoihdJC8RsfK1ds7.jpg",
        "release_date": "2021-04-07",
        "title": "Mortal Kombat",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 3527,
        "trailer":"Y2O4RCdwCGM"
    },
    {
        "adult": false,
        "backdrop_path": "/zm2kMjiz0u6qdn2XKbEbQkDiltN.jpg",
        "genre": "Terror" ,
        "id": 675024,
        "original_language": "es",
        "original_title": "El exorcismo de Carmen Farías",
        "overview": "Carmen descubre que su abuela le ha dejado algo más que una casa como herencia.",
        "popularity": 833.588,
        "poster_path": "/pMyOSRURkxF6YId9vOTGsBH1jRb.jpg",
        "release_date": "2021-07-05",
        "title": "El exorcismo de Carmen Farías",
        "video": false,
        "vote_average": 6.3,
        "vote_count": 50,
        "trailer":"h1jRDSuqQlc"
    },
    {
        "adult": false,
        "backdrop_path": "/6FzuNrApEc71aJ3CwwkpadbNled.jpg",
        "genre": "Accion" ,
        "id": 581644,
        "original_language": "en",
        "original_title": "The Misfits",
        "overview": "Después de ser reclutado por un grupo de ladrones poco convencionales, el renombrado criminal Richard Pace se ve envuelto en un elaborado atraco de oro que promete tener implicaciones de gran alcance en su vida y en la vida de muchos otros.",
        "popularity": 804.52,
        "poster_path": "/y3pmIbrIFhLfTplrxpAo0S1tY1b.jpg",
        "release_date": "2021-06-10",
        "title": "Ladrones de Elite",
        "video": false,
        "vote_average": 5.4,
        "vote_count": 101,
        "trailer":"vWnker2dBQE"
    },
    {
        "adult": false,
        "backdrop_path": "/zsH3iW60T1t2HBTtrSKzzxJ406J.jpg",
        "genre": "Animado" ,
        "id": 846214,
        "original_language": "en",
        "original_title": "The Simpsons: The Good, the Bart, and the Loki",
        "overview": "Loki es desterrado de Asgard una vez más y debe enfrentarse a sus oponentes más duros hasta el momento: Los Simpson y los héroes más poderosos de Springfield. El Dios del engaño se une a Bart Simpson en el evento crossover definitivo que rinde homenaje al universo cinematográfico de superhéroes y villanos de Marvel”",
        "popularity": 794.709,
        "poster_path": "/u10ZfFwbCMB4UrFy7OlHq08fBRr.jpg",
        "release_date": "2021-07-07",
        "title": "Los Simpson: La buena, el malo y Loki",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 343,
        "trailer":"AE-RP7_USjM"
    }
]
}
